import './style.css';
import './mobile.css';
import { dailySeed, exits, label, makeBoard, rotate, solved, type Board } from './game';

const app=document.querySelector<HTMLDivElement>('#app')!;
let board: Board;
let turns=0, selected=0, demo=false, muted=false, won=false, boardName='Today’s tide', tutorialStep=0;
let running=true, last=performance.now(), lag=0;
const storage=()=> `${demo?'demo:':'tide:'}tide-and-tile`;
const escape=(s:string)=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!));

function route(){ return location.pathname.replace(/\/$/,'')||'/'; }
function titleFor(path:string){ return path==='/privacy'?'Privacy — Tide & Tile':path==='/terms'?'Terms — Tide & Tile':path==='/demo'?'Demo — Tide & Tile':'Tide & Tile — Make a daily harbor route'; }
function nav(){ return `<header><a class="skip" href="#main">Skip to puzzle</a><a class="wordmark" href="/" data-link>TIDE <i>&</i> TILE</a><nav aria-label="Main navigation"><a href="/demo" data-link>Demo</a><a href="#archive">Archive</a><a href="/privacy" data-link>Privacy</a></nav></header>`; }
function footer(){return `<footer><p>A daily harbor-route puzzle for short calm breaks.</p><p><a href="/privacy" data-link>Privacy</a> · <a href="/terms" data-link>Terms</a> · Built by Param Factory · v1.0</p><small>Harbor illustration is AI-generated original artwork.</small></footer>`;}
function docPage(kind:'privacy'|'terms'){
 const privacy=kind==='privacy';
 return `${nav()}<main id="main" tabindex="-1" class="legal"><h1>${privacy?'Privacy at Tide & Tile':'Terms for Tide & Tile'}</h1><p>${privacy?'Your game progress stays in this browser.':'Use Tide & Tile for personal, non-commercial play.'}</p><h2>${privacy?'What we store':'What you may expect'}</h2><p>${privacy?'We store completed boards, your best turn count, and sound preference in local storage. Demo data uses a separate browser key and is discarded when you leave demo mode. We do not use accounts, analytics, ads, or third-party requests.':'The game is free. It is provided as-is without a promise of uninterrupted availability. The artwork and game code may not be copied for commercial use.'}</p><h2>${privacy?'How to remove it':'Contact'}</h2><p>${privacy?'Use your browser’s site-data controls to remove Tide & Tile data.':'For a product question, contact Param Factory through its public site.'}</p></main>${footer()}`;
}
function appPage(){return `${nav()}${demo?`<aside class="demo-banner" aria-label="Demo status"><b>Demo — sample data, nothing is saved</b><button id="reset-demo">Reset demo</button><button id="start-real">Start for real</button></aside>`:''}<main id="main" tabindex="-1"><section class="hero"><div><p class="eyebrow">DAILY HARBOR PUZZLE</p><h1>Make today’s harbor route</h1><p class="intro">For casual players who want a calm puzzle break with clear rules.</p><div class="actions"><a class="button primary" href="/demo" data-link>Try it with sample data</a><span>Loads a guided board. Nothing is saved.</span></div><ul class="facts"><li>Free to play</li><li>Works offline after the first visit</li><li>Your progress stays here</li></ul></div><figure><img src="/harbor-table.webp" width="768" height="512" alt="A harbor puzzle table with blue water tiles and a chart." loading="eager" fetchpriority="high"><figcaption>Turn the channels. Join the harbor.</figcaption></figure></section><section class="game-zone" aria-labelledby="game-title"><div class="game-heading"><div><p class="eyebrow">${demo?'SAMPLE BOARD':'DAILY BOARD'}</p><h2 id="game-title">${boardName}</h2></div><div class="statbar"><span>Turns <b id="turns">${turns}</b></span><span>Fewest <b id="par">${board.par}</b></span><button id="sound" aria-pressed="${muted}">${muted?'Sound off':'Sound on'}</button></div></div><p id="tip" class="tip" aria-live="polite">${tipText()}</p><div id="board" class="board" role="grid" aria-label="Harbor tile board"></div><div class="game-actions"><button id="restart">Restart this board</button><button id="help">Show the next rule</button><button id="share" ${won?'':'disabled'}>Copy result</button></div><p id="result" class="result" aria-live="polite"></p></section><section id="archive" class="archive"><div><p class="eyebrow">ANY DAY, ANY TIME</p><h2>Archive boards</h2><p>Practice the rules on three saved routes.</p></div><div class="archive-buttons"><button data-archive="Dock lesson">Dock lesson <small>One turn</small></button><button data-archive="Breakwater bend">Breakwater bend <small>Some corners</small></button><button data-archive="Harbor circuit">Harbor circuit <small>Full route</small></button></div></section><section class="how"><h2>How to play Tide & Tile</h2><ol><li><b>Turn</b> a tile by tapping it or pressing Enter.</li><li><b>Join</b> every water channel from dock to harbor.</li><li><b>Finish</b> with fewer turns to earn a medal.</li></ol><p><b>What it does not do:</b> no timers, lives, accounts, or leaderboards. Your browser keeps your own progress.</p></section></main>${footer()}`}
function tipText(){if(won)return `Harbor route complete in ${turns} turns.`;if(tutorialStep===1)return `First rule: turn a tile until its water points toward the next tile. Seed ${board.seed}.`;if(tutorialStep===2)return `Second rule: every water end must meet another water end. Seed ${board.seed}.`;if(tutorialStep===3)return `Third rule: solve it again with fewer turns. Seed ${board.seed}.`;return `Seed ${board.seed}. Tap a tile to turn its water channel. Use arrow keys to move between tiles.`;}
function renderBoard(){ const el=document.querySelector<HTMLDivElement>('#board')!; el.removeAttribute('role'); el.innerHTML=''; board.tiles.forEach((tile,i)=>{ const b=document.createElement('button'); b.className='tile'; b.dataset.i=String(i); b.setAttribute('aria-label',`Row ${Math.floor(i/4)+1}, column ${i%4+1}: ${label(tile)}. Press to rotate.`); b.style.setProperty('--turn',`${tile.rotation*90}deg`); b.innerHTML=`<svg viewBox="0 0 100 100" aria-hidden="true"><path class="channel ${tile.kind}" d="${tile.kind==='straight'?'M50 0V100':'M50 0V50H100'}"/></svg>`; b.addEventListener('click',()=>turnTile(i)); b.addEventListener('keydown',tileKeys); el.append(b); }); }
function tileKeys(e:KeyboardEvent){ const index=Number((e.currentTarget as HTMLElement).dataset.i); const keys:{[key:string]:number}={ArrowRight:1,ArrowLeft:-1,ArrowDown:4,ArrowUp:-4}; if(e.key in keys){e.preventDefault(); selected=Math.max(0,Math.min(15,index+keys[e.key])); renderBoard(); (document.querySelector(`[data-i="${selected}"]`) as HTMLButtonElement)?.focus();} }
function turnTile(i:number){ if(won)return; board=rotate(board,i); turns++; selected=i; if(solved(board)){won=true; saveProgress(); sayResult();} renderBoard(); updateStats(); chirp(); }
function updateStats(){document.querySelector('#turns')!.textContent=String(turns); const t=document.querySelector('#tip')!; t.textContent=tipText(); const s=document.querySelector<HTMLButtonElement>('#share')!; s.disabled=!won;}
function sayResult(){const medal=turns<=board.par?'Tide medal':turns<=board.par+5?'Harbor medal':'Dock medal'; document.querySelector('#result')!.textContent=`Route complete. ${medal}. ${turns} turns; fewest is ${board.par}.`;}
function start(seed=dailySeed(), name='Today’s tide', tutorial=0){board=makeBoard(seed,tutorial);boardName=name;turns=0;won=false;}
function saveProgress(){try{localStorage.setItem(storage(),JSON.stringify({seed:board.seed,best:turns,muted}));}catch{}}
function restore(){try{const v=JSON.parse(localStorage.getItem(storage())||'{}'); muted=Boolean(v.muted);}catch{}}
function chirp(){if(muted)return; const C=window.AudioContext||(window as any).webkitAudioContext; if(!C)return; const c=new C(), o=c.createOscillator(), g=c.createGain(); o.frequency.value=440;g.gain.setValueAtTime(.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.06);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.06);}
function bind(){ document.querySelectorAll<HTMLAnchorElement>('[data-link]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault(); history.pushState({},'',a.href); render();})); document.querySelector('#restart')?.addEventListener('click',()=>{start(board.seed,boardName);renderBoard();updateStats();document.querySelector('#result')!.textContent='Board restarted.';});document.querySelector('#help')?.addEventListener('click',()=>{document.querySelector('#tip')!.textContent='A straight channel has two opposite ends. A corner joins two neighboring edges.';});document.querySelector('#sound')?.addEventListener('click',()=>{muted=!muted; saveProgress();render();});document.querySelector('#share')?.addEventListener('click',async()=>{const text=`Tide & Tile ${board.seed}\n${turns} turns · fewest ${board.par}\n🌊 🟦 🌊`;try{await navigator.clipboard.writeText(text);document.querySelector('#result')!.textContent='Result copied. Share only your turn count.';}catch{document.querySelector('#result')!.textContent=text;}});document.querySelector('#reset-demo')?.addEventListener('click',()=>{localStorage.removeItem('demo:tide-and-tile');start('sample-harbor','Sample harbor',1);render();});document.querySelector('#start-real')?.addEventListener('click',()=>{localStorage.removeItem('demo:tide-and-tile');history.pushState({},'','/');render();});document.querySelectorAll<HTMLButtonElement>('[data-archive]').forEach(b=>b.addEventListener('click',()=>{start(`archive-${b.dataset.archive}`,b.dataset.archive!,b.dataset.archive==='Dock lesson'?1:0);render();document.querySelector('#game-title')?.scrollIntoView({behavior:'smooth'});})); }
function render(){const path=route();document.title=titleFor(path); if(path==='/privacy'||path==='/terms'){app.innerHTML=docPage(path.slice(1) as 'privacy'|'terms');}else{demo=path==='/demo';restore();if(demo){tutorialStep=1;}else{const visitKey='tide:tide-and-tile:visits';const visits=Number(localStorage.getItem(visitKey)||'0');tutorialStep=Math.min(3,visits+1);localStorage.setItem(visitKey,String(visits+1));}start(demo?'sample-harbor':dailySeed(),demo?'Sample harbor':'Today’s tide',tutorialStep===1?1:0);app.innerHTML=appPage();renderBoard();bind();} requestAnimationFrame(()=>{const h1=document.querySelector<HTMLElement>('h1');h1?.setAttribute('tabindex','-1');h1?.focus();});}
function loop(now:number){if(running){lag+=Math.min(100,now-last);while(lag>=1000/60)lag-=1000/60;}last=now;requestAnimationFrame(loop);}document.addEventListener('visibilitychange',()=>{running=!document.hidden;last=performance.now();});window.addEventListener('popstate',render);render();requestAnimationFrame(loop);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
